name: container ci

on:
  push:
    branches:
      - main

jobs:
  dynamic:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Github Container
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to Multiple Registries
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/pwa-modular-auction:latest
